version: '3'

services:
  pycontw-2021-frontend:
    container_name: pycontw-2021-frontend
    restart: always
    build:
      context: .
    ports:
      - "3000:3000"

networks:
    default:
        external:
            name: pycontw-net
